name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: Run tests
      run: npm test
      if: runner.os != 'Linux'
  build:
    needs:
    - test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Package
      run: npm run package
    - name: Store artifact
      uses: actions/upload-artifact@v3
      with:
        name: vscode-extension
        path: actionable-*.vsix
        if-no-files-found: error
